// P3.T9: simple position+time wind field for Thailand.
//
// Pure module — no THREE dependency. currentWind() takes a position-like
// {x, z} and a sim-time scalar and returns the local wind vector in world
// frame, along with the meteorological "from" direction and magnitude.
//
// Sign / axis conventions (matches Drone.forward() in src/drone.js):
//   +X = east        +Z = south
//   -X = west        -Z = north
// Meteorology: "wind from 270°" means it BLOWS FROM the west, so its
// velocity vector points east (+X). Conversion:
//   vec.x = -sin(dirRad) · speed     // 270° → +speed east
//   vec.z = +cos(dirRad) · speed     // 0°/360° (from N) → +speed south
//
// Spatial / temporal variation is generated by summing two slow sinusoids
// on each of the (dirNoise, speedNoise) axes — produces a smooth,
// non-repeating-feeling field without dragging in a Perlin implementation.
// The X/Z scale (100 km) and time scale (60 s) match the playbook spec's
// `perlin(x/10000, z/10000, t/60)` shape after re-scaling for Thailand's
// ~1500 km extent (a few cycles end-to-end, not dozens).

export const DEFAULT_WIND = Object.freeze({
  enabled: true,
  /** Prevailing wind FROM direction (meteorological). Default = Thai SW monsoon. */
  baseDirDeg: 220,
  /** Prevailing wind speed (m/s). ~12 kt = 6.2 m/s. */
  baseSpeedMs: 6.2,
  /** Maximum ± deviation in direction from the noise field. */
  variabilityDirDeg: 15,
  /** Maximum ± deviation in speed from the noise field. */
  variabilityMs: 2.5,
});

const X_SCALE = 100_000;   // metres per spatial cycle (X axis)
const Z_SCALE = 100_000;   // metres per spatial cycle (Z axis)
const T_SCALE = 60;        // seconds per temporal cycle

// Two-component scalar noise, output range ~[-1, +1]. Sum of two
// out-of-phase sinusoids with co-prime frequencies → no obvious tiling.
function _noiseDir(nx, nz, nt) {
  const a = Math.sin(nx + nz * 0.7 + nt);
  const b = Math.sin(nx * 0.6 - nz * 1.3 + nt * 0.8 + 1.7);
  return (a + 0.7 * b) / 1.7;
}
function _noiseSpd(nx, nz, nt) {
  const a = Math.cos(nx * 0.9 + nz * 0.4 + nt * 0.6);
  const b = Math.cos(nx * 1.1 - nz * 0.8 + nt * 1.2 + 1.0);
  return (a + 0.6 * b) / 1.6;
}

// Altitude wind profile — speed multiplier knots and veer table.
// Contract (B10.T7): ×1.0 ≤ 500 m, ×1.5 @ 3 km, ×2.0 @ 6 km, ×2.8 @ 11 km;
// linear interpolation between segments; clamped at ×2.8 above 11 km.
// Veer: +15° per 3,000 m for alt > 500 m (dead-band keeps ≤500 m parity).
const _ALT_KNOTS = [
  [500,    1.0],
  [3_000,  1.5],
  [6_000,  2.0],
  [11_000, 2.8],
];

/**
 * Returns the speed multiplier and veer (degrees clockwise) for a given
 * altitude in metres. At ≤ 500 m both are exactly their surface values
 * (×1.0, 0°) to preserve strict surface-parity.
 */
function _altProfile(altM) {
  const alt = Math.max(0, altM);

  // Speed multiplier via piecewise linear interpolation.
  let mul = 1.0;
  if (alt <= _ALT_KNOTS[0][0]) {
    mul = 1.0;
  } else if (alt >= _ALT_KNOTS[_ALT_KNOTS.length - 1][0]) {
    mul = _ALT_KNOTS[_ALT_KNOTS.length - 1][1];
  } else {
    for (let i = 0; i < _ALT_KNOTS.length - 1; i++) {
      const [a0, m0] = _ALT_KNOTS[i];
      const [a1, m1] = _ALT_KNOTS[i + 1];
      if (alt >= a0 && alt <= a1) {
        const t = (alt - a0) / (a1 - a0);
        mul = m0 + t * (m1 - m0);
        break;
      }
    }
  }

  // Veer: 15° per 3 km, dead-band at ≤ 500 m for strict surface parity.
  const veerDeg = alt > 500 ? (15 / 3_000) * alt : 0;

  return { mul, veerDeg };
}

/**
 * Sample the wind field at (position, time).
 * @param {{x:number, y:number, z:number}} position World-frame position (y = altitude m).
 * @param {number} time Sim seconds (monotonic).
 * @param {object} [settings] Override DEFAULT_WIND fields (e.g. for tests).
 * @returns {{
 *   vec3: { x:number, z:number },   // velocity bias in m/s, world frame
 *   speedMs: number,
 *   dirDeg: number,                  // meteorological "from" direction
 * }}
 */
export function currentWind(position, time, settings) {
  const s = settings ?? DEFAULT_WIND;
  if (!s.enabled) {
    return { vec3: { x: 0, z: 0 }, speedMs: 0, dirDeg: 0 };
  }
  const nx = (position?.x ?? 0) / X_SCALE;
  const nz = (position?.z ?? 0) / Z_SCALE;
  const nt = (time ?? 0) / T_SCALE;

  const dirNoise = _noiseDir(nx, nz, nt);
  const spdNoise = _noiseSpd(nx, nz, nt);

  // Surface wind (base layer, identical to pre-B10 at ≤ 500 m).
  const dirRawDeg = s.baseDirDeg + dirNoise * s.variabilityDirDeg;
  const surfDirDeg = ((dirRawDeg % 360) + 360) % 360;
  const surfSpeedMs = Math.max(0, s.baseSpeedMs + spdNoise * s.variabilityMs);

  // Altitude profile: multiplier + veer.
  const altM = position?.y ?? 0;
  const { mul, veerDeg } = _altProfile(altM);

  const speedMs = surfSpeedMs * mul;
  const dirDeg = ((surfDirDeg + veerDeg) % 360 + 360) % 360;

  const rad = (dirDeg * Math.PI) / 180;
  return {
    vec3: { x: -Math.sin(rad) * speedMs, z: Math.cos(rad) * speedMs },
    speedMs,
    dirDeg,
  };
}
