// P3.T9: simple position+time wind field for Thailand.
//
// Pure module — no THREE dependency. currentWind() takes a position-like
// {x, z} and a sim-time scalar and returns the local wind vector in world
// frame, along with the meteorological "from" direction and magnitude.
//
// Sign / axis conventions (matches Drone.forward() in src/drone.js):
//   +X = east        +Z = south
//   -X = west        -Z = north
// Meteorology: "wind from 270°" means it BLOWS FROM the west, so its
// velocity vector points east (+X). Conversion:
//   vec.x = -sin(dirRad) · speed     // 270° → +speed east
//   vec.z = +cos(dirRad) · speed     // 0°/360° (from N) → +speed south
//
// Spatial / temporal variation is generated by summing two slow sinusoids
// on each of the (dirNoise, speedNoise) axes — produces a smooth,
// non-repeating-feeling field without dragging in a Perlin implementation.
// The X/Z scale (100 km) and time scale (60 s) match the playbook spec's
// `perlin(x/10000, z/10000, t/60)` shape after re-scaling for Thailand's
// ~1500 km extent (a few cycles end-to-end, not dozens).

export const DEFAULT_WIND = Object.freeze({
  enabled: true,
  /** Prevailing wind FROM direction (meteorological). Default = Thai SW monsoon. */
  baseDirDeg: 220,
  /** Prevailing wind speed (m/s). ~12 kt = 6.2 m/s. */
  baseSpeedMs: 6.2,
  /** Maximum ± deviation in direction from the noise field. */
  variabilityDirDeg: 15,
  /** Maximum ± deviation in speed from the noise field. */
  variabilityMs: 2.5,
});

const X_SCALE = 100_000;   // metres per spatial cycle (X axis)
const Z_SCALE = 100_000;   // metres per spatial cycle (Z axis)
const T_SCALE = 60;        // seconds per temporal cycle

// Two-component scalar noise, output range ~[-1, +1]. Sum of two
// out-of-phase sinusoids with co-prime frequencies → no obvious tiling.
function _noiseDir(nx, nz, nt) {
  const a = Math.sin(nx + nz * 0.7 + nt);
  const b = Math.sin(nx * 0.6 - nz * 1.3 + nt * 0.8 + 1.7);
  return (a + 0.7 * b) / 1.7;
}
function _noiseSpd(nx, nz, nt) {
  const a = Math.cos(nx * 0.9 + nz * 0.4 + nt * 0.6);
  const b = Math.cos(nx * 1.1 - nz * 0.8 + nt * 1.2 + 1.0);
  return (a + 0.6 * b) / 1.6;
}

/**
 * Sample the wind field at (position, time).
 * @param {{x:number, z:number}} position World-frame position.
 * @param {number} time Sim seconds (monotonic).
 * @param {object} [settings] Override DEFAULT_WIND fields (e.g. for tests).
 * @returns {{
 *   vec3: { x:number, z:number },   // velocity bias in m/s, world frame
 *   speedMs: number,
 *   dirDeg: number,                  // meteorological "from" direction
 * }}
 */
export function currentWind(position, time, settings) {
  const s = settings ?? DEFAULT_WIND;
  if (!s.enabled) {
    return { vec3: { x: 0, z: 0 }, speedMs: 0, dirDeg: 0 };
  }
  const nx = (position?.x ?? 0) / X_SCALE;
  const nz = (position?.z ?? 0) / Z_SCALE;
  const nt = (time ?? 0) / T_SCALE;

  const dirNoise = _noiseDir(nx, nz, nt);
  const spdNoise = _noiseSpd(nx, nz, nt);

  const dirRawDeg = s.baseDirDeg + dirNoise * s.variabilityDirDeg;
  const dirDeg = ((dirRawDeg % 360) + 360) % 360;
  const speedMs = Math.max(0, s.baseSpeedMs + spdNoise * s.variabilityMs);

  const rad = (dirDeg * Math.PI) / 180;
  return {
    vec3: { x: -Math.sin(rad) * speedMs, z: Math.cos(rad) * speedMs },
    speedMs,
    dirDeg,
  };
}
